sudo: required
notifications:
    email: false
language: generic
script:
    - curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash

arch:
  packages:
    - python-dbus
    - python-gobject
    - python-pytest
    - python-pytest-cov
    - python-coverage
    - dbus-glib
  script:
    - tests/run.sh
